apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: tammam95/my-app:f10fa509b78ff1fa85bf2393d6f80c50c1f71a6f
        ports:
        - containerPort: 3000

