apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: tammam95/my-app:241c082972f50bac48b0121945b7ca0a91e52d56
        ports:
        - containerPort: 3000

