apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: tammam95/my-app:9827e8c2183182492e348ccd0e8e23f30b3e7570
        ports:
        - containerPort: 3000

